CREATE TABLE Departments (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Building INT NOT NULL CHECK (Building BETWEEN 1 AND 5),
    Financing MONEY NOT NULL DEFAULT 0,
    Name NVARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE Diseases (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE,
    Severity INT NOT NULL CHECK (Severity >= 1) DEFAULT 1
);
CREATE TABLE Doctors (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(MAX) NOT NULL,
    Phone CHAR(10) NOT NULL,
    Salary MONEY NOT NULL CHECK (Salary >= 0),
    Surname NVARCHAR(MAX) NOT NULL
);
CREATE TABLE Examinations (
    ID INT PRIMARY KEY IDENTITY(1,1),
    DayOfWeek INT NOT NULL CHECK (DayOfWeek BETWEEN 1 AND 7),
    EndTime TIME NOT NULL,
    Name NVARCHAR(100) NOT NULL UNIQUE,
    StartTime TIME NOT NULL CHECK (StartTime >= '08:00' AND StartTime <= '18:00')
);